pub mod align;
pub mod binarize;
pub mod binary_ip;
#[cfg(feature = "hash")]
pub mod hash;
pub mod l2;
#[cfg(feature = "linear")]
pub mod linear;
pub mod minmax;
pub mod norm;
pub mod ord32;
pub mod projection;
pub mod quantize;
